### ISSUE TITLE
Next.js Feature Implementation Tracking

### ISSUE THREAD

**Issue by andrew-bierman** [andrew-bierman/PackRat#633]
Track and manage the implementation of key features for Next.js app.

Feature List
- [ ] Cloudflare nextjs support - https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/ 
- [ ] Implement new web specific features - raghavyuva's landing page (need to pull page onto clean branch to fix conflicts). Better responsive, floating navbar.  
- [ ] tRPC Pre-Fetching data - Need to implement solution that allows for pre-fetch on next, but still support client fetch on native https://trpc.io/docs/client/nextjs/server-side-helpers

**Comment by taronaleksanian** [comment]
Working on
 Implement floating navbar like tamagui site utilizes
